/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.quintech.app;

import com.quintech.app.Except.TestExcepts;

public class App {
    public static void main(String[] args) throws InterruptedException {
        TestExcepts.run();
    }
}
